############################################################
# Scenario overrides for a 10-node experiment.
############################################################
@include=template.properties

logfile=10.log
seed=0
bootstrap_nodes=10
