############################################################
# Scenario overrides for the test network.
############################################################
@include=template.properties

logfile=test.log
bootstrap_nodes=500
bootstrap_blocks=500
profile.medium.hubness=0.1
profile.hub.hubness=0.8
